version: '3.10'

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres_db
    env_file:
      - .env
